package com.smartarchive.archivemanage.service;

import com.smartarchive.archivemanage.dto.AiModelConfigResponse;
import com.smartarchive.archivemanage.dto.ArchiveAskCommand;
import com.smartarchive.archivemanage.dto.ArchiveAskResponse;
import com.smartarchive.archivemanage.dto.ArchiveAttachmentResponse;
import com.smartarchive.archivemanage.dto.ArchiveAttachmentUpdateCommand;
import com.smartarchive.archivemanage.dto.ArchiveCreateCommand;
import com.smartarchive.archivemanage.dto.ArchiveCreateOptionsResponse;
import com.smartarchive.archivemanage.dto.ArchiveCreateSessionCommand;
import com.smartarchive.archivemanage.dto.ArchiveCreateSessionResponse;
import com.smartarchive.archivemanage.dto.ArchiveDefaultResolveResponse;
import com.smartarchive.archivemanage.dto.ArchiveQueryCommand;
import com.smartarchive.archivemanage.dto.ArchiveQueryResponse;
import com.smartarchive.archivemanage.dto.ArchiveSummaryResponse;
import com.smartarchive.archivemanage.dto.ArchiveTransferCommand;
import com.smartarchive.archivemanage.dto.ArchiveTransferResponse;
import com.smartarchive.archivemanage.dto.PendingAuditAttachmentRef;
import com.smartarchive.archivemanage.dto.PendingAuditDownload;
import com.smartarchive.archivemanage.dto.PendingDocumentBatchDeleteCommand;
import com.smartarchive.archivemanage.dto.PendingDocumentWriteCommand;
import com.smartarchive.archivemanage.dto.BindBatchResponse;
import com.smartarchive.archivemanage.dto.BindCreateCommand;
import com.smartarchive.archivemanage.dto.BindOptionsResponse;
import com.smartarchive.archivemanage.dto.BindPreviewCommand;
import com.smartarchive.archivemanage.dto.BindPreviewResponse;
import com.smartarchive.archivemanage.dto.BindQueryCommand;
import com.smartarchive.archivemanage.dto.StorageBatchResponse;
import com.smartarchive.archivemanage.dto.StorageCreateCommand;
import com.smartarchive.archivemanage.dto.StorageLedgerQueryCommand;
import com.smartarchive.archivemanage.dto.StorageLedgerResponse;
import com.smartarchive.archivemanage.dto.StorageOptionsResponse;
import com.smartarchive.archivemanage.dto.StorageQueryCommand;
import com.smartarchive.archivemanage.dto.StorageQueryResponse;
import com.smartarchive.workspace.dto.WorkspaceIoJobSummaryResponse;
import java.util.List;
import org.springframework.web.multipart.MultipartFile;

public interface ArchiveManagementService {
    ArchiveCreateOptionsResponse loadCreateOptions();
    ArchiveDefaultResolveResponse resolveDefaults(String companyProjectCode, String busiModuleCode, String customRule, String archiveDestination);
    ArchiveCreateSessionResponse createSession(ArchiveCreateSessionCommand command);
    ArchiveCreateSessionResponse getSession(String sessionCode);
    ArchiveAttachmentResponse uploadAttachment(String sessionCode, String attachmentRole, String attachmentTypeCode, String remark, MultipartFile file);
    ArchiveAttachmentResponse updateAttachment(String sessionCode, Long attachmentId, ArchiveAttachmentUpdateCommand command);
    ArchiveSummaryResponse createArchive(ArchiveCreateCommand command);
    ArchiveQueryResponse queryArchives(ArchiveQueryCommand command);
    ArchiveAskResponse ask(ArchiveAskCommand command);
    List<AiModelConfigResponse> listAiModels();
    ArchiveSummaryResponse getArchiveDetail(Long archiveId);
    ArchiveSummaryResponse createPendingDocument(PendingDocumentWriteCommand command);
    ArchiveSummaryResponse updatePendingDocument(Long docId, PendingDocumentWriteCommand command);
    void deletePendingDocuments(PendingDocumentBatchDeleteCommand command, long operatorUserId);
    ArchiveSummaryResponse duplicatePendingDocument(Long sourceDocId, long operatorUserId);
    PendingAuditAttachmentRef uploadPendingAuditAttachment(MultipartFile file);
    PendingAuditDownload downloadPendingAuditAttachment(Long fileId, String storageKey);
    PendingAuditDownload downloadArchiveAttachment(Long attachmentId);
    PendingAuditDownload previewArchiveAttachment(Long attachmentId);
    PendingAuditDownload downloadArchiveAttachmentsZip(Long archiveId);
    WorkspaceIoJobSummaryResponse createPendingDocumentsExportJob(List<Long> docIds, String exportFileFormat, String exportScope, Long operatorUserId);
    WorkspaceIoJobSummaryResponse submitArchiveImportQueryJob(MultipartFile file, String documentTypeCode, Long operatorUserId);
    ArchiveTransferResponse transferArchives(ArchiveTransferCommand command);
    BindOptionsResponse loadBindOptions();
    BindPreviewResponse previewBind(BindPreviewCommand command);
    BindBatchResponse createBindBatch(BindCreateCommand command);
    BindBatchResponse getBindBatch(String bindBatchCode);
    List<BindBatchResponse> queryBindBatches(BindQueryCommand command);
    StorageOptionsResponse loadStorageOptions();
    StorageQueryResponse queryStorage(StorageQueryCommand command);
    StorageBatchResponse createStorageBatch(StorageCreateCommand command);
    StorageBatchResponse getStorageBatch(String storageBatchCode);
    List<StorageLedgerResponse> queryStorageLedger(StorageLedgerQueryCommand command);
    StorageLedgerResponse getStorageLedger(Long ledgerId);
}
