package com.smartarchive.common.audit.domain;

import jakarta.persistence.*;
import lombok.Data;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;

@Data
@Entity
@Table(name = "fdc_audit_log_t")
@EntityListeners(AuditingEntityListener.class)
public class AuditLog {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "audit_log_id")
    private Long auditLogId;

    @Column(name = "object_id", nullable = false)
    private Long objectId;

    @Column(name = "object_type", length = 30, nullable = false)
    private String objectType; // e.g., DOCUMENT, VOLUME

    @Column(name = "operation_type", length = 30, nullable = false)
    private String operationType; // e.g., CREATE, UPDATE, DELETE

    @Column(name = "operation_details")
    private String operationDetails; // JSON or text for detailed changes

    @Column(name = "operator_id")
    private Long operatorId;

    @Column(name = "operator_name", length = 100)
    private String operatorName;

    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    @CreatedBy
    @Column(name = "created_by", length = 100, nullable = false, updatable = false)
    private String createdBy;

    @CreatedDate
    @Column(name = "created_date", nullable = false, updatable = false)
    private LocalDateTime createdDate;

    @LastModifiedBy
    @Column(name = "last_modified_by", length = 100)
    private String lastModifiedBy;

    @LastModifiedDate
    @Column(name = "last_modified_date")
    private LocalDateTime lastModifiedDate;

    @Version
    @Column(name = "version")
    private Integer version;

    @Column(name = "enable_flag", length = 1, nullable = false)
    private String enableFlag = "Y"; // Y/N

    // Getters and Setters are generated by Lombok's @Data
}
